title:              FernandoBDansi Blog
email:              fernandobuenodansi@gmail.com
description:        Um lugar para compartilhar conhecimentos!
author:             Fernando Bueno Dansi
domain:             "blog.fbdansi.dev.br"
baseurl:            "/blog"
url:                "https://fernandobdansi.github.io"

# Social Profiles
twitter_username:   fernandobdansi
github_username:    fernandobdansi
facebook_username:  fernandobdansi
instagram_username: fernandobdansi
linkedin_username:  fernandobdansi

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
